$OSInfo = Get-WmiObject -Class Win32_OperatingSystem
$OSLanguage = $OSInfo.OSLanguage
#$OSLanguage

switch ( $OSLanguage )

{

    0 { $language = 'Unicode' }
    1025 { $language = 'Arabic - Saudi Arabia' }
    1026 { $language = 'Bulgarian' }
    1027 { $language = 'Catalan' }
    1028 { $language = 'Chinese - Taiwan' }
    1029 { $language = 'Czech' }
    1030 { $language = 'Danish' }
    1031 { $language = 'German - Germany' }
    1032 { $language = 'Greek' }
    1033 { $language = 'English - United States' }
    1034 { $language = 'Spanish - Spain (Traditional)' }
    1035 { $language = 'Finnish' }
    1036 { $language = 'French - France' }
    1037 { $language = 'Hebrew' }
    1038 { $language = 'Hungarian' }
    1039 { $language = 'Icelandic' }
    1040 { $language = 'Italian - Italy' }
    1041 { $language = 'Japanese' }
    1042 { $language = 'Korean' }
    1043 { $language = 'Dutch - Netherlands' }
    1044 { $language = 'Norwegian - Bokml' }
    1045 { $language = 'Polish' }
    1046 { $language = 'Portuguese - Brazil' }
    1047 { $language = 'Raeto-Romance' }
    1048 { $language = 'Romanian - Romania' }
    1049 { $language = 'Russian' }
    1050 { $language = 'Croatian' }
    1051 { $language = 'Slovak' }
    1052 { $language = 'Albanian' }
    1053 { $language = 'Swedish - Sweden' }
    1054 { $language = 'Thai' }
    1055 { $language = 'Turkish' }
    1056 { $language = 'Urdu' }
    1057 { $language = 'Indonesian' }
    1058 { $language = 'Ukrainian' }
    1059 { $language = 'Belarusian' }
    1060 { $language = 'Slovenian' }
    1061 { $language = 'Estonian' }
    1062 { $language = 'Latvian' }
    1063 { $language = 'Lithuanian' }
    1064 { $language = 'Tajik' }
    1065 { $language = 'Farsi - Persian' }
    1066 { $language = 'Vietnamese' }
    1067 { $language = 'Armenian' }
    1068 { $language = 'Azeri - Latin' }
    1069 { $language = 'Basque' }
    1070 { $language = 'Sorbian' }
    1071 { $language = 'FYRO Macedonia' }
    1072 { $language = 'Sesotho (Sutu)' }
    1073 { $language = 'Tsonga' }
    1074 { $language = 'Setsuana' }
    1075 { $language = 'Venda' }
    1076 { $language = 'Xhosa' }
    1077 { $language = 'Zulu' }
    1078 { $language = 'Afrikaans' }
    1079 { $language = 'Georgian' }
    1080 { $language = 'Faroese' }
    1081 { $language = 'Hindi' }
    1082 { $language = 'Maltese' }
    1083 { $language = 'Sami Lappish' }
    1084 { $language = 'Gaelic - Scotland' }
    1085 { $language = 'Yiddish' }
    1086 { $language = 'Malay - Malaysia' }
    1087 { $language = 'Kazakh' }
    1088 { $language = 'Kyrgyz - Cyrillic' }
    1089 { $language = 'Swahili' }
    1090 { $language = 'Turkmen' }
    1091 { $language = 'Uzbek - Latin' }
    1092 { $language = 'Tatar' }
    1093 { $language = 'Bengali - India' }
    1094 { $language = 'Punjabi' }
    1095 { $language = 'Gujarati' }
    1096 { $language = 'Oriya' }
    1097 { $language = 'Tamil' }
    1098 { $language = 'Telugu' }
    1099 { $language = 'Kannada' }
    1100 { $language = 'Malayalam' }
    1101 { $language = 'Assamese' }
    1102 { $language = 'Marathi' }
    1103 { $language = 'Sanskrit' }
    1104 { $language = 'Mongolian' }
    1105 { $language = 'Tibetan' }
    1106 { $language = 'Welsh' }
    1107 { $language = 'Khmer' }
    1108 { $language = 'Lao' }
    1109 { $language = 'Burmese' }
    1110 { $language = 'Galician' }
    1111 { $language = 'Konkani' }
    1112 { $language = 'Manipuri' }
    1113 { $language = 'Sindhi' }
    1114 { $language = 'Syriac' }
    1118 { $language = 'Amharic' }
    1120 { $language = 'Kashmiri' }
    1121 { $language = 'Nepali' }
    1122 { $language = 'Frisian - Netherlands' }
    1124 { $language = 'Filipino' }
    1126 { $language = 'Edo' }
    1136 { $language = 'Igbo - Nigeria' }
    1140 { $language = 'Guarani - Paraguay' }
    1142 { $language = 'Latin' }
    1143 { $language = 'Somali' }
    1153 { $language = 'Maori' }
    1279 { $language = 'HID (Human Interface Device)' }
    2049 { $language = 'Arabic - Iraq' }
    2052 { $language = 'Chinese - China' }
    2055 { $language = 'German - Switzerland' }
    2057 { $language = 'English - Great Britain' }
    2058 { $language = 'Spanish - Mexico' }
    2060 { $language = 'French - Belgium' }
    2064 { $language = 'Italian - Switzerland' }
    2067 { $language = 'Dutch - Belgium' }
    2068 { $language = 'Norwegian - Nynorsk' }
    2070 { $language = 'Portuguese - Portugal' }
    2072 { $language = 'Romanian - Moldova' }
    2073 { $language = 'Russian - Moldova' }
    2074 { $language = 'Serbian - Latin' }
    2077 { $language = 'Swedish - Finland' }
    2092 { $language = 'Azeri - Cyrillic' }
    2108 { $language = 'Gaelic - Ireland' }
    2110 { $language = 'Malay - Brunei' }
    2115 { $language = 'Uzbek - Cyrillic' }
    2117 { $language = 'Bengali - Bangladesh' }
    2128 { $language = 'Mongolian' }
    3073 { $language = 'Arabic - Egypt' }
    3076 { $language = 'Chinese - Hong Kong SAR' }
    3079 { $language = 'German - Austria' }
    3081 { $language = 'English - Australia' }
    3084 { $language = 'French - Canada' }
    3098 { $language = 'Serbian - Cyrillic' }
    4097 { $language = 'Arabic - Libya' }
    4100 { $language = 'Chinese - Singapore' }
    4103 { $language = 'German - Luxembourg' }
    4105 { $language = 'English - Canada' }
    4106 { $language = 'Spanish - Guatemala' }
    4108 { $language = 'French - Switzerland' }
    5121 { $language = 'Arabic - Algeria' }
    5124 { $language = 'Chinese - Macau SAR' }
    5127 { $language = 'German - Liechtenstein' }
    5129 { $language = 'English - New Zealand' }
    5130 { $language = 'Spanish - Costa Rica' }
    5132 { $language = 'French - Luxembourg' }
    5146 { $language = 'Bosnian' }
    6145 { $language = 'Arabic - Morocco' }
    6153 { $language = 'English - Ireland' }
    6154 { $language = 'Spanish - Panama' }
    6156 { $language = 'French - Monaco' }
    7169 { $language = 'Arabic - Tunisia' }
    7177 { $language = 'English - Southern Africa' }
    7178 { $language = 'Spanish - Dominican Republic' }
    7180 { $language = 'French - West Indies' }
    8193 { $language = 'Arabic - Oman' }
    8201 { $language = 'English - Jamaica' }
    8202 { $language = 'Spanish - Venezuela' }
    9217 { $language = 'Arabic - Yemen' }
    9225 { $language = 'English - Caribbean' }
    9226 { $language = 'Spanish - Colombia' }
    9228 { $language = 'French - Congo' }
    10241 { $language = 'Arabic - Syria' }
    10249 { $language = 'English - Belize' }
    10250 { $language = 'Spanish - Peru' }
    10252 { $language = 'French - Senegal' }
    11265 { $language = 'Arabic - Jordan' }
    11273 { $language = 'English - Trinidad' }
    11274 { $language = 'Spanish - Argentina' }
    11276 { $language = 'French - Cameroon' }
    12289 { $language = 'Arabic - Lebanon' }
    12297 { $language = 'English - Zimbabwe' }
    12298 { $language = 'Spanish - Ecuador' }
    12300 { $language = 'French - Cote d Ivoire' }
    13313 { $language = 'Arabic - Kuwait' }
    13321 { $language = 'English - Philippines' }
    13322 { $language = 'Spanish - Chile' }
    13324 { $language = 'French - Mali' }
    14337 { $language = 'Arabic - United Arab Emirates' }
    14346 { $language = 'Spanish - Uruguay' }
    14348 { $language = 'French - Morocco' }
    15361 { $language = 'Arabic - Bahrain' }
    15370 { $language = 'Spanish - Paraguay' }
    16385 { $language = 'Arabic - Qatar' }
    16393 { $language = 'English - India' }
    16394 { $language = 'Spanish - Bolivia' }
    17418 { $language = 'Spanish - El Salvador' }
    18442 { $language = 'Spanish - Honduras' }
    19466 { $language = 'Spanish - Nicaragua' }
    20490 { $language = 'Spanish - Puerto Rico' }
    dv { $language = 'Divehi' }
    si { $language = 'Sinhala' }
}

Write-Output $language
